### ISSUE TITLE
Not working on Android chrome browser

### ISSUE THREAD

**Issue by nanda248** [knxyzkn/react-browser-notifications#2]
May I know how I can use this notification feature on Android chrome browser? 
It's working fine on my desktop browser. When I tested this demo page (https://react-notif-demo.herokuapp.com/home) on my mobile chrome, the notification is not working as well. 
May I know how i can make it work?

**Comment by knxyzkn** [comment]
Hi @nanda248, This package is intended for desktop browsers and is not supported in mobile browsers. On mobile devices, I would recommend that you use native notifications, such iOS's push notifications, etc.
